#!/bin/bash
set -e

# Variables to define
#BASE_PATH  // container mount path. Generated by blackbox: /mnt/{serviceName}-{volumeName}
#REPO // testrepo
#KEEP // Number of images to keep
#TAG_PREFIX // Optional

echo "Variables:"
for ARGUMENT in "$@"; do
    KEY=$(echo $ARGUMENT | cut -f1 -d=)
    VALUE=$(echo $ARGUMENT | cut -f2 -d=)
    declare $KEY="$VALUE"
    echo $KEY="$VALUE"
done

REGISTRY_REPO_PATH="/docker/registry/v2/repositories"
REGISTRY_IMAGE_PATH="/_manifests/tags"
REGISTRY_IMAGE_FULL_PATH=$BASE_PATH$REGISTRY_REPO_PATH/$REPO$REGISTRY_IMAGE_PATH

IMAGE_DIRS=($(sudo ls -A1t $REGISTRY_IMAGE_FULL_PATH | grep -P "("$TAG_PREFIX".?)"))

for i in "${!IMAGE_DIRS[@]}"; do
    CURRENT_DIR=${IMAGE_DIRS[i]}
    if [[ $i -gt $(($KEEP - 1)) ]]; then
        echo "Deleting $REPO:$CURRENT_DIR"
        sudo rm -Rf $REGISTRY_IMAGE_FULL_PATH/$CURRENT_DIR
        RESTART="yes"
    else
        echo "Keeping image: $REPO:$CURRENT_DIR"
    fi
done

if [ "$RESTART" = "yes" ]; then
    echo "Cleaning up"
    sudo microk8s kubectl rollout restart deployment/docker-registry
fi
